$f = "c:\Users\Saad Ahmed\Desktop\new1\index.html"
$c = [System.IO.File]::ReadAllText($f, [System.Text.Encoding]::UTF8)
$start = $c.IndexOf("<!-- ===================== TRUST STRIP ===================== -->")
$end = $c.IndexOf("</section>", $start) + 10

$newSection = "    <!-- ===================== TRUST STRIP ===================== -->`n    <section class=""trust-strip"" aria-label=""Trusted brands"">`n      <div class=""container""><p class=""strip-title"">Trusted by businesses worldwide. Built for growth.</p></div>`n      <div class=""brands-marquee-wrap"">`n        <div class=""brands-track"">`n          <div class=""brand-item""><span class=""brand-google"">Google</span></div>`n          <div class=""brand-item""><span class=""brand-amazon"">amazon</span></div>`n          <div class=""brand-item""><span class=""brand-microsoft"">Microsoft</span></div>`n          <div class=""brand-item""><span class=""brand-shopify"">Shopify</span></div>`n          <div class=""brand-item""><span class=""brand-meta"">Meta</span></div>`n          <div class=""brand-item""><span class=""brand-stripe"">stripe</span></div>`n          <div class=""brand-item""><span class=""brand-slack"">Slack</span></div>`n          <div class=""brand-item""><span class=""brand-netflix"">NETFLIX</span></div>`n          <div class=""brand-item""><span class=""brand-airbnb"">airbnb</span></div>`n          <div class=""brand-item""><span class=""brand-uber"">Uber</span></div>`n          <div class=""brand-item""><span class=""brand-spotify"">Spotify</span></div>`n          <div class=""brand-item""><span class=""brand-paypal"">PayPal</span></div>`n          <div class=""brand-item""><span class=""brand-google"">Google</span></div>`n          <div class=""brand-item""><span class=""brand-amazon"">amazon</span></div>`n          <div class=""brand-item""><span class=""brand-microsoft"">Microsoft</span></div>`n          <div class=""brand-item""><span class=""brand-shopify"">Shopify</span></div>`n          <div class=""brand-item""><span class=""brand-meta"">Meta</span></div>`n          <div class=""brand-item""><span class=""brand-stripe"">stripe</span></div>`n          <div class=""brand-item""><span class=""brand-slack"">Slack</span></div>`n          <div class=""brand-item""><span class=""brand-netflix"">NETFLIX</span></div>`n          <div class=""brand-item""><span class=""brand-airbnb"">airbnb</span></div>`n          <div class=""brand-item""><span class=""brand-uber"">Uber</span></div>`n          <div class=""brand-item""><span class=""brand-spotify"">Spotify</span></div>`n          <div class=""brand-item""><span class=""brand-paypal"">PayPal</span></div>`n        </div>`n      </div>`n    </section>"

$newContent = $c.Substring(0, $start) + $newSection + $c.Substring($end)
[System.IO.File]::WriteAllText($f, $newContent, [System.Text.Encoding]::UTF8)
Write-Host "Done"
