$f = "c:\Users\Saad Ahmed\Desktop\new1\style.css"
$c = [System.IO.File]::ReadAllText($f, [System.Text.Encoding]::UTF8)
$start = $c.IndexOf("/* ===================== HEADER ===================== */")
$end = $c.IndexOf(".header-inner {")

$newBlock = "/* ===================== HEADER ===================== */`n.header {`n  position: sticky;`n  top: 0;`n  z-index: 50;`n  background: rgba(255,255,255,.97);`n  backdrop-filter: blur(16px);`n  border-bottom: 1px solid var(--line);`n  transition: background .35s ease, box-shadow .35s ease, border-color .35s ease;`n}`n`n/* TOP STATE: white bg, blue links */`n.header:not(.scrolled) .nav-link         { color: #334155; }`n.header:not(.scrolled) .nav-link:hover,`n.header:not(.scrolled) .nav-link.active  { color: var(--blue); }`n.header:not(.scrolled) .nav-link::after  { background: var(--blue); }`n.header:not(.scrolled) .logo-text strong { color: var(--text); }`n.header:not(.scrolled) .logo-text small  { color: var(--muted); }`n.header:not(.scrolled) .logo-mark        { background: var(--grad); color: #fff; }`n.header:not(.scrolled) .menu-toggle      { background: #fff; border-color: var(--line); }`n.header:not(.scrolled) .menu-toggle span { background: var(--text); }`n`n/* SCROLLED STATE: navy blue bg + white links */`n.header.scrolled {`n  background: rgba(6,42,92,.92);`n  backdrop-filter: blur(18px);`n  border-bottom-color: rgba(255,255,255,.1);`n  box-shadow: 0 8px 32px rgba(3,27,61,.4);`n}`n.header.scrolled .nav-link         { color: rgba(255,255,255,.85); }`n.header.scrolled .nav-link:hover,`n.header.scrolled .nav-link.active  { color: #fff; }`n.header.scrolled .nav-link::after  { background: #fff; }`n.header.scrolled .logo-text strong { color: #fff; }`n.header.scrolled .logo-text small  { color: rgba(255,255,255,.55); }`n.header.scrolled .logo-mark        { background: rgba(255,255,255,.12); color: #fff; }`n.header.scrolled .menu-toggle      { background: rgba(255,255,255,.1); border-color: rgba(255,255,255,.25); }`n.header.scrolled .menu-toggle span { background: #fff; }`n.header.scrolled .btn-primary      { background: #fff; color: var(--blue); box-shadow: none; }`n.header.scrolled .btn-primary:hover{ background: var(--light); }`n`n"

$newContent = $c.Substring(0, $start) + $newBlock + $c.Substring($end)
[System.IO.File]::WriteAllText($f, $newContent, [System.Text.Encoding]::UTF8)
Write-Host "Done"
